name: Keep-Alive Deploy for Vercel

on:
  schedule:
    - cron: '0 0 */25 * *'  # Ejecuta cada 25 días (ajusta el número si quieres)
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Auto: Keep-alive deploy [skip ci]"
          git push
